apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  startingDeadlineSeconds: 15  #  CronJob controller checks things every 10 seconds
  concurrencyPolicy: Allow  # Forbid || Replace
  suspend: false  # Set to true to suspend the CronJob
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  timeZone: "Asia/Kuala_Lumpur"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
