FROM node:alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy index.js to the working directory
COPY index.js ./

# Expose the port to app runs on
EXPOSE 3000

# Command to run the application
CMD ["node", "index.js"]